<a href="https://colab.research.google.com/github/Yubinex/tensorflow-coursework/blob/master/00_tensorflow_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals Exercises

In [1]:
import tensorflow as tf

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [3]:
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
vector = tf.constant([1, 2, 3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [6]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[1, 2, 3],
                       [4, 5, 6]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

## 2. Find the shape, rank and size of the tensor you created in 1.

In [13]:
print(f"Display shape of tensor: {tensor.shape}")
print(f"Display rank of tensor; {tf.rank(tensor)}")
print(f"Display size of tensor: {tf.size(tensor)}")

Display shape of tensor: (2, 2, 3)
Display rank of tensor; 3
Display size of tensor: 12


## 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [16]:
tf.random.set_seed(42)
random_tensor_0 = tf.random.uniform((5, 300))
random_tensor_1 = tf.random.uniform((5, 300))
random_tensor_0, random_tensor_0.shape, random_tensor_1, random_tensor_1.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [18]:
tf.linalg.matmul(random_tensor_0, tf.transpose(random_tensor_1))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product.

In [22]:
tf.tensordot(random_tensor_0, tf.transpose(random_tensor_1), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [33]:
large_tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
large_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

## 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [34]:
print(f"Max value: {tf.reduce_max(large_tensor)}")
print(f"Min value: {tf.reduce_min(large_tensor)}")

Max value: 0.9999972581863403
Min value: 1.1444091796875e-05


## 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [38]:
large_tensor_2 = tf.random.uniform(shape=[1, 224, 224, 3])
print(f"Shape before: {large_tensor_2.shape}")
large_tensor_2 = tf.squeeze(large_tensor_2)
print(f"Shape after: {large_tensor_2.shape}")

Shape before: (1, 224, 224, 3)
Shape after: (224, 224, 3)


## 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [39]:
another_tensor = tf.constant([4, 2, 7, 4, 2, 4, 34, 2, 1, 23])
tf.argmax(another_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

## 10. One-hot encode the tensor you created in 9.

In [43]:
tf.one_hot(another_tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>